### ISSUE TITLE
How to specify which signer to send fulfillOrder function from?

### ISSUE THREAD

**Issue by 0xFloop** [ProjectOpenSea/seaport-js#104]
Within the docs is says that the accountAddress is the "optional address from which to fulfill the order from", however, when testing, the transactions are 1. giving "cannot estimate gas" error, 2. attempting to be sent from the offerer address and not the specified fulfiller address.
```
 const { executeAllActions: executeAllFulfillActions } =
    await seaport.fulfillOrder({
      order,
      accountAddress: fulfiller.address,
    });

  const transaction = executeAllFulfillActions();
```
This is the code being used (directly from the docs). I can provide more of the code being used if necessary

**Comment by Slokh** [comment]
So this looks right to me? Can you provide more code for context -- i.e. how you are initializing seaport?

**Comment by 0xFloop** [comment]
Yep thank you, I have tried initializing via signers and jsonrpcprovider. 
```
  [fulfiller, offerer] = await ethers.getSigners();

  const seaport = new Seaport(offerer);
  ```
Tried with both signers, this method seems to send all tx's from the signer initialized with. And gives the aforementioned "cannot estimate gas" error whilst assumedly incorrectly trying to send the fulfillOrder call from the offerer address .
```
  const provider = new ethers.providers.JsonRpcProvider(
    "https://eth-goerli.g.alchemy.com/v2/<API_KEY>"
  );

  const seaport = new Seaport(provider);
  ```
  
  This option just errors out when trying to create order, I assume because its trying to use the address of the provider as signer.
  
  Here is the entire code being run, just a simple create order from one address, fulfill from another. Specifically it is being ran on Goerli.
  
  ```
  const { ethers } = require("hardhat");
const { Seaport } = require("@opensea/seaport-js");
const dotenv = require("dotenv");
const util = require("util");

dotenv.config();
Error.stackTraceLimit = Infinity;

const minterTokenId = 1;

let tokenAddress = <ERC721_TOKEN_ADDRESS>;

const main = async () => {
  const provider = new ethers.providers.JsonRpcProvider(
    "https://eth-goerli.g.alchemy.com/v2/<API_KEY>"
  );

  [fulfiller, offerer] = await ethers.getSigners();

  const seaport = new Seaport(offerer);

  const nftId = "1";

  console.log("Offerer address: " + offerer.address + ": HOLDS 3 NFT'S");
  console.log("Fulfiller address: " + fulfiller.address);

  const { executeAllActions } = await seaport.createOrder(
    {
      offer: [
        {
          itemType: 2, //erc721
          token: tokenAddress,
          identifier: nftId,
        },
      ],
      consideration: [
        {
          amount: ethers.utils.parseEther("0.1").toString(),
          recipient: offerer.address,
        },
      ],
    },
    offerer.address
  );
  const order = await executeAllActions();
  const { executeAllActions: executeAllFulfillActions } =
    await seaport.fulfillOrder({
      order,
      accountAddress: fulfiller.address,
    });

  const transaction = executeAllFulfillActions();
};

main();
```

**Comment by sunwrobert** [comment]
> Yep thank you, I have tried initializing via signers and jsonrpcprovider.
> 
> ```
>   [fulfiller, offerer] = await ethers.getSigners();
> 
>   const seaport = new Seaport(offerer);
> ```
> 
> Tried with both signers, this method seems to send all tx's from the signer initialized with. And gives the aforementioned "cannot estimate gas" error whilst assumedly incorrectly trying to send the fulfillOrder call from the offerer address .
> 
> ```
>   const provider = new ethers.providers.JsonRpcProvider(
>     "https://eth-goerli.g.alchemy.com/v2/<API_KEY>"
>   );
> 
>   const seaport = new Seaport(provider);
> ```
> 
> This option just errors out when trying to create order, I assume because its trying to use the address of the provider as signer.
> 
> Here is the entire code being run, just a simple create order from one address, fulfill from another. Specifically it is being ran on Goerli.
> 
> ```
> const { ethers } = require("hardhat");
> const { Seaport } = require("@opensea/seaport-js");
> const dotenv = require("dotenv");
> const util = require("util");
> 
> dotenv.config();
> Error.stackTraceLimit = Infinity;
> 
> const minterTokenId = 1;
> 
> let tokenAddress = <ERC721_TOKEN_ADDRESS>;
> 
> const main = async () => {
> const provider = new ethers.providers.JsonRpcProvider(
>   "https://eth-goerli.g.alchemy.com/v2/<API_KEY>"
> );
> 
> [fulfiller, offerer] = await ethers.getSigners();
> 
> const seaport = new Seaport(offerer);
> 
> const nftId = "1";
> 
> console.log("Offerer address: " + offerer.address + ": HOLDS 3 NFT'S");
> console.log("Fulfiller address: " + fulfiller.address);
> 
> const { executeAllActions } = await seaport.createOrder(
>   {
>     offer: [
>       {
>         itemType: 2, //erc721
>         token: tokenAddress,
>         identifier: nftId,
>       },
>     ],
>     consideration: [
>       {
>         amount: ethers.utils.parseEther("0.1").toString(),
>         recipient: offerer.address,
>       },
>     ],
>   },
>   offerer.address
> );
> const order = await executeAllActions();
> const { executeAllActions: executeAllFulfillActions } =
>   await seaport.fulfillOrder({
>     order,
>     accountAddress: fulfiller.address,
>   });
> 
> const transaction = executeAllFulfillActions();
> };
> 
> main();
> ```

@0xFloop  Why are you initializing it with a signer? When you initialize it with a signer it assumes that you're going to be using that signer for all your methods. Whether that is a correct assumption or not is left for debate. It was mainly introduced to support consumers who didn't have access to a `provider`, but instead just a `signer`. Just initialize your seaport with a `provider` (`ethers.providers.JsonRpcProvider`), and then it'll work.

**Comment by 0xFloop** [comment]
Okay thankyou, at first try, like stated in the initial issue post, using a provider gives me a `Error: bad response` error when trying to run the `const order = await executeAllActions();` code. I'll try to debug that and comment again here if I have further issue. Again, thank you very much for the help!

**Comment by 0xFloop** [comment]
@sunwrobert So i run into the ```The method eth_signTypedData_v4 does not exist/is not available``` error response from rpc provider when running the ```const order = await executeAllActions();``` code. Openzeppelin docs say this issue is due to the signing request being forwarded to the rpc node opposed to the hardhat accounts indicated. Accounts setup in config and are imported normally so I am not sure why this would be causing an error. Any thoughts?
```
    goerli: {
      url: process.env.ALCHEMY_TESTNET_RPC_URL,
      accounts: [
        `${process.env.GOERLI_PRIVATE_KEY_FULFILLER}`,
        `${process.env.GOERLI_PRIVATE_KEY_OFFERER}`,
      ],
    },
```

**Comment by 0xFloop** [comment]
I see this code entails that it is trying to get the signers from the alchemy provider? How does that work?
```
  private _getSigner(accountAddress?: string): Signer {
    if (this.signer) {
      return this.signer;
    }

    if (!(this.provider instanceof providers.JsonRpcProvider)) {
      throw new Error("Either signer or a JsonRpcProvider must be provided");
    }

    return this.provider.getSigner(accountAddress);
  }
```

**Comment by 0xFloop** [comment]
I've gotten it working via metamask, but would love to be able to work with it in a script and not rely on metamask / ui

**Comment by bartttiii** [comment]
Did you manage to fix the switch account issue yet? I am running into the same issue. Seaport wont recognize ethers as a valid provider

**Comment by 0xFloop** [comment]
@bartttiii No i never sorted out the issue with signer selection, however, the package is much easier to use via a ui and a browser based wallet. Heres a simple react app i made that may help you https://github.com/0xFloop/seaport-sig-ui

**Comment by bartttiii** [comment]
@0xFloop Ah I see what youre doing. I noticed that too.. I can't seem to make get Seaport tol isten to a Provider which is a not a Signer like you exactly did:
` let provider = new ethers.providers.Web3Provider(window.ethereum, "any");`
`TypeError: provider.getNetwork is not a function`

Thanks though

**Comment by DEREK-DEV-AFK** [comment]
Guys Don't get confuse look here is my script and its completely working fine.

[script](https://github.com/DEREK-DEV-AFK/NFT_Transfer-Seaport/blob/master/index.js)
