### ISSUE TITLE
The fulfiller does not have the balances needed to fulfill.

### ISSUE THREAD

**Issue by pguardiario** [ProjectOpenSea/seaport-js#105]
Can someone help me understand why I get this error? 
I'm trying to buy a nft that's listed on opensea.
The fulfiller is the owner of the nft, correct?
I verified that the owner address is right.
The message sounds like seaport thinks the owner doesn't have that token...

```
const provider = new ethers.providers.Web3Provider(window.ethereum)
const seaport = new Seaport(provider)
let [account] = await window.ethereum.enable()

const offerer = account // me
const fulfiller = "0x3649b5fA32d367BfAf218354cf5eB7Ab55AE1c46" // the address that owns the token

const { executeAllActions } = await seaport.createOrder(
  {
    offer: [
      {
        amount: ethers.utils.parseEther("0.0019").toString(),
        recipient: fulfiller,
      },
    ],
    consideration: [
      {
        itemType: 2, //ItemType.ERC721,
        token: "0x42921c64797b64499a3ad3a3cdbbfab7bee294fe",
        identifier: "1262",
        recipient: offerer,
      },
    ],
  },
  offerer
)

const order = await executeAllActions()
console.log(order)

const { executeAllActions: executeAllFulfillActions } =
  await seaport.fulfillOrder({
    order,
    accountAddress: account,
  });

const transaction = executeAllFulfillActions();

```

**Comment by srslafazan** [comment]
Same 👍

**Comment by BravoNatalie** [comment]
I was with the impression that the fulfiller and the offerer are the same, but I'm also with this error.

**Comment by pguardiario** [comment]
I don't think the seaport team is interested in posting working code for
some reason... If someone knows a non-opensea solution I would love to see
it posted here.

**Comment by DEREK-DEV-AFK** [comment]
Hey i solved this error, Let me explain,
In the first code block you are creating an order which says that you are providing some ETH in return you want an NFT.
this will be run successfully, since you are creating it.
But in the second block you are fulfilling it, but since you are calling the fulfill order not the person who owns that NFT, That why you are getting an error here. 

I hope you understand it. Please do let me know you solved it or not.

**Comment by emorling** [comment]
> Hey i solved this error, Let me explain, In the first code block you are creating an order which says that you are providing some ETH in return you want an NFT. this will be run successfully, since you are creating it. But in the second block you are fulfilling it, but since you are calling the fulfill order not the person who owns that NFT, That why you are getting an error here.
> 
> I hope you understand it. Please do let me know you solved it or not.

Awesome please provide a code example

**Comment by DEREK-DEV-AFK** [comment]
Here is the link to my script file.

I have created 2 instances for interaction with 2 different accounts.


Here is the link 
[link](https://github.com/DEREK-DEV-AFK/NFT_Transfer-Seaport/blob/master/index.js)

**Comment by pguardiario** [comment]
> Hey i solved this error, Let me explain, In the first code block you are creating an order which says that you are providing some ETH in return you want an NFT. this will be run successfully, since you are creating it. But in the second block you are fulfilling it, but since you are calling the fulfill order not the person who owns that NFT, That why you are getting an error here.
> 
> I hope you understand it. Please do let me know you solved it or not.

No, the order I created matched an active listing on opensea and I'm trying to fulfill it. And I'm trying to do it from frontend.

**Comment by DEREK-DEV-AFK** [comment]
Of that you must need the order obj to fulfil it. And please check the consideration part that must be required to fulfil that order.

Well i think i have done the same thing, but actually i created order and the fulfil it.even if its not working please share your code for better understanding of your problem. So i can help you in an better way.

Have a great day ahead 👋

**Comment by pguardiario** [comment]
I shared it at the top. I'm just trying to buy an NFT that's already listed.

**Comment by Maumasi** [comment]
> Hey i solved this error, Let me explain, In the first code block you are creating an order which says that you are providing some ETH in return you want an NFT. this will be run successfully, since you are creating it. But in the second block you are fulfilling it, but since you are calling the fulfill order not the person who owns that NFT, That why you are getting an error here.
> 
> I hope you understand it. Please do let me know you solved it or not.

I think I understand. From this explanation, it sounds like the `seaport.createOrder ` block is a bidding/buy order. Separately, the short `seaport.fulfillOrder ` block is the other side of that transaction that a seller would make.

It is confusing because the Seaport-js docs show the example as one full process to execute a bid/buy order.

While I not getting the error anymore because I'm not trying to run the `seaport.fulfillOrder` block as the bidder. Though, I'm not seeing the order show up on Opensea even though I can see that the order has been verified by following up the `order` with:
```
const validated = seaport.validate([order]);
const transaction = await validated.transact();
console.log('validated: ', await transaction.wait());
```

**Comment by scqsu** [comment]
> > > Hey i solved this error, Let me explain, In the first code block you are creating an order which says that you are providing some ETH in return you want an NFT. this will be run successfully, since you are creating it. But in the second block you are fulfilling it, but since you are calling the fulfill order not the person who owns that NFT, That why you are getting an error here.
> > > I hope you understand it. Please do let me know you solved it or not.
> > 
> > 
> > I think I understand. From this explanation, it sounds like the `seaport.createOrder ` block is a bidding/buy order. Separately, the short `seaport.fulfillOrder ` block is the other side of that transaction that a seller would make.
> > It is confusing because the Seaport-js docs show the example as one full process to execute a bid/buy order.
> > While I not getting the error anymore because I'm not trying to run the `seaport.fulfillOrder` block as the bidder. Though, I'm not seeing the order show up on Opensea even though I can see that the order has been verified by following up the `order` with:
> > ```
> > const validated = seaport.validate([order]);
> > const transaction = await validated.transact();
> > console.log('validated: ', await transaction.wait());
> > ```
> 
> yes

do you know how to fulfill a listed nft item ( this nft was already on opensea marketplace) ?

The scenario is i'm a buyer, i want to buy listed item on opensea through seaport-js.

**Comment by scqsu** [comment]
> Can someone help me understand why I get this error? I'm trying to buy a nft that's listed on opensea. The fulfiller is the owner of the nft, correct? I verified that the owner address is right. The message sounds like seaport thinks the owner doesn't have that token...
> 
> ```
> const provider = new ethers.providers.Web3Provider(window.ethereum)
> const seaport = new Seaport(provider)
> let [account] = await window.ethereum.enable()
> 
> const offerer = account // me
> const fulfiller = "0x3649b5fA32d367BfAf218354cf5eB7Ab55AE1c46" // the address that owns the token
> 
> const { executeAllActions } = await seaport.createOrder(
>   {
>     offer: [
>       {
>         amount: ethers.utils.parseEther("0.0019").toString(),
>         recipient: fulfiller,
>       },
>     ],
>     consideration: [
>       {
>         itemType: 2, //ItemType.ERC721,
>         token: "0x42921c64797b64499a3ad3a3cdbbfab7bee294fe",
>         identifier: "1262",
>         recipient: offerer,
>       },
>     ],
>   },
>   offerer
> )
> 
> const order = await executeAllActions()
> console.log(order)
> 
> const { executeAllActions: executeAllFulfillActions } =
>   await seaport.fulfillOrder({
>     order,
>     accountAddress: account,
>   });
> 
> const transaction = executeAllFulfillActions();
> ```

hi, do you solve this problem ?

**Comment by DEREK-DEV-AFK** [comment]
This doesn't work like that, owner himself have to make an order and sign by himself and user have to creat other order.
For example:
Owner has 1 NFT
In order to sell this nft, the owner need to create an order where he will specify that he will give this nft and in return what he wants.
And if the same consideration matches by an buyer where the buyer want that nft and he is giving the same thing what owner wants then only the transaction will be successful.
