### ISSUE TITLE
My Orders on OpenSea

### ISSUE THREAD

**Issue by JoshuaAlvarez06** [ProjectOpenSea/seaport-js#113]
Hey!
After reading this tweet that was posted on the OpenSea account (https://twitter.com/opensea/status/1570482796271140864) I had some questions.

What listings/offers will be fulfillable on OpenSea?  Does this refer to the orders created with the `createBuyOrder` function in this library?
If it is not referring to these orders, then what listings are being referred to in this tweet?

My use-case would be me having my own dapp where I can create orders using `seaport-js` for others to fulfill only on my dapp.

**Comment by sunwrobert** [comment]
If the listing you call `validate` passes OpenSea's validations i.e., has the 2.5% OpenSea fee as well, correct collection fee, as the valid OpenSea zone, then we'd ingest it.
