### ISSUE TITLE
Type Error

### ISSUE THREAD

**Issue by aditya-angadi-artemis** [ProjectOpenSea/seaport-js#116]
I get the error 
"listings/SeaportEthListing.ts:24:33 - error TS2345: Argument of type 'JsonRpcProvider' is not assignable to parameter of type 'JsonRpcProvider | Signer'." 

however the code snippet is very straightforward as in tutorials
```
import {ethers} from "ethers";
import { Seaport } from "@opensea/seaport-js";


    const provider = new ethers.providers.JsonRpcProvider(
        `https://eth-goerli.g.alchemy.com/v2/${process.env.ALCHEMY_KEY}`
    );
    
       const seaport = new Seaport(provider);
       
       ```
       
  "ethers": "^5.5.4",
    "@opensea/seaport-js": "^1.0.6",

**Comment by kornelHub** [comment]
Try to upgrade ethers to ^5.7.1 version. I used your code with this version and it didn't throw any errors.

**Comment by aditya-angadi-artemis** [comment]
Thanks a lot
