### ISSUE TITLE
[question] Should the README example work?

### ISSUE THREAD

**Issue by aquaflamingo** [ProjectOpenSea/seaport-js#131]
Hi there,

Thanks for creating this library. I'm trying to run the code in the example to just understand how the library and seaport work, however, on running the code in the example as is using an RPC provider (Infura) for `Seaport` I receive an error back with:

```plaintext
call revert exception 
[ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] 
(method=\"ownerOf(uint256)\", data=\"0x\", errorArgs=null, 
errorName=null, errorSignature=null, reason=null, 
code=CALL_EXCEPTION, version=abi/5.7.0)
```

I'm assuming that the error has something to do with a call to a contract `ownerOf` but it doesn't specify _which_ contract (i.e. Seaport or ERC[20/721/1155]). After adding some logging to the `seaport-js` library distribution and tracing through, I managed to find the failure point at the checking approvals step [here](https://github.com/ProjectOpenSea/seaport-js/blob/6348a21652324889cf852010f9f6da88042aaad1/src/utils/balanceAndApprovalCheck.ts#L82-L98). 

My understanding is this step should check, if all library defaults are taken, whether the offerer account has given the default Seaport Conduit Key approval permission to transfer the [Doodles ERC721](https://etherscan.io/address/0x8a90cab2b38dba80c64b7734e58ee1db38b8992e), but instead it seems like the contract call fails with a revert.

Unfortunately the RPC provider doesn't have any better but would appreciate any better ideas if you have any. I'm running the example on Goerli network.

**Comment by aquaflamingo** [comment]
Example code from README:
```
const offerer = "0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266";
const fulfiller = "0x70997970c51812dc3a010c7d01b50e0d17dc79c8";
const { executeAllActions } = await seaport.createOrder(
  {
    offer: [
      {
        itemType: ItemType.ERC721,
        token: "0x8a90cab2b38dba80c64b7734e58ee1db38b8992e",
        identifier: "1",
      },
    ],
    consideration: [
      {
        amount: ethers.utils.parseEther("10").toString(),
        recipient: offerer,
      },
    ],
  },
  offerer
);

const order = await executeAllActions();

const { executeAllActions: executeAllFulfillActions } =
  await seaport.fulfillOrder({
    order,
    accountAddress: fulfiller,
  });

const transaction = executeAllFulfillActions();
```

**Comment by aquaflamingo** [comment]
Confirmed that if you test the library with a testnet token contract it at least gets to an error message 👍

**Comment by sunwrobert** [comment]
Go for it!
