### ISSUE TITLE
Rounding error in `mapOrderAmountsFromUnitsToFill`

### ISSUE THREAD

**Issue by 0xMasayoshi** [ProjectOpenSea/seaport-js#141]
There is a potential rounding error when calculating offer/consideration amounts in `mapOrderAmountsFromUnitsToFill`.
&nbsp;  
Consider the following example:
- Alice creates a partially fillable order, listing 3 of some ERC1155 token for 1ETH each
- Bob tries to buy 1 of these tokens by calling `seaport.fulfillOrder`
- In this scenario, `seaport.fulfillOrder` will execute `fulfillAdvancedOrder` on the Seaport contract with a value of 0.9999ETH, resulting in InsufficientEtherSupplied error

---

Let's examine why this is happening using the following snippets from `mapOrderAmountsFromUnitsToFill` as reference:
```
const unitsToFillBasisPoints = unitsToFillBn
    .mul(ONE_HUNDRED_PERCENT_BP)
    .div(maxUnits);
```
&&
```
const multiplyBasisPoints = (amount: BigNumberish, basisPoints: BigNumberish) =>
  BigNumber.from(amount)
    .mul(BigNumber.from(basisPoints))
    .div(ONE_HUNDRED_PERCENT_BP);
```
&&
```
startAmount: multiplyBasisPoints(
    item.startAmount,
    basisPoints
).toString(),
```

When Bob executes `seaport.fulfillOrder` the following calculations are made:
- `unitsToFillBasisPoints = 1 * 10_000 / 3 = 3333.3333333333333333 = 3333 (due to BigNumber truncation)`
- `startAmount: 3E18 * 3333 / 10_000 = 0.9999E17 = 0.9999ETH`

Because BigNumber does not support decimals, the precision of `unitsToFillBasisPoints` is off, resulting in a rounding error when calculating the consideration's start and end amounts.

**Comment by adeebabdulsalam** [comment]
what is maxUnits ? is it the length of offer / consideration or startAmount/endAmount.
I faced this error when my offer is partially fillable ERC1155 token (startAmount: around 100)
unitsToFill =1 , and consideration length =3 (payment,commission and royalty).

I hope there is a fix soon

**Comment by luisantoniocrag** [comment]
Is there some temporally solution?

**Comment by xtools-at** [comment]
created PR #197 together with @wooglie to solve this issue, please read the limitations stated in the description
