### ISSUE TITLE
seaport.createOrder don't work

### ISSUE THREAD

**Issue by Ghijo1** [ProjectOpenSea/seaport-js#181]
Hello, this is my code but i don't get any error message and seaport dont list my NFT:

`const Seaport = require("@opensea/seaport-js").Seaport;
const ethers = require("ethers").ethers;

const provider = new ethers.providers.JsonRpcProvider(
  "https://eth-mainnet.g.alchemy.com/v2/MY_ALKEMY_API_KEY"
);

const signer = new ethers.Wallet("MY_WALLET_PRIVATE_KEY", provider);

const seaport = new Seaport(signer,{seaportVersion:"1.4", apiKey: "MY_OS_API_KEY"});

const offerer = "MY_WALLET_ADDRESS";

async function main(){

    const { executeAllActions } = await seaport.createOrder(
        {
        offer: [
            {
            itemType: 2,
            token: "CONTRACT_ADDRESS",
            identifier: "TOKEN_ID",
            },
        ],
        consideration: [
            {
            amount: ethers.utils.parseEther("10").toString(),
            recipient: offerer,
            },
        ],
        },
        offerer
    );

    const order = await executeAllActions();
}

main()`

Can someone help me? 
Thank you in advance

**Comment by toekneema** [comment]
what is the error you're getting? i am able to createOrder() and executeAllActions(), but i get stuck on fulfillOrder()
