### ISSUE TITLE
There is a bug in the mapOrderAmountsFromUnitsToFill method, when it encounters a case like 10000/3.

### ISSUE THREAD

**Issue by tercel** [ProjectOpenSea/seaport-js#185]
The mapOrderAmountsFromUnitsToFill function means to calculate the amount needed for partial transactions.
Using multiplyBasisPoints  to calculate amount is inaccuracy, 
// i.e if totalFilled is 3 and totalSize is 4, there are 1 / 4 order amounts left to fill.
  const basisPoints = totalSize.sub(totalFilled).mul(ONE_HUNDRED_PERCENT_BP).div(totalSize);
for example, totalSize=3, totalFilled=2, ONE_HUNDRED_PERCENT_BP=10000 
basisPoints = 333, can't get rid of it all.

It should be modified as follows:
`+ const multiplyDivision = (amount: BigNumberish, numerator: BigNumberish, denominator: BigNumberish) =>`
`+   BigNumber.from(amount).mul(BigNumber.from(numerator)).div(denominator);`

`- startAmount: multiplyBasisPoints(item.endAmount, basisPoints).toString(),`
`+ startAmount: multiplyDivision(item.startAmount, unitsToFillBn, totalSize).toString(),`
`- endAmount: multiplyBasisPoints(item.endAmount, basisPoints).toString(),`
`+ endAmount: multiplyDivision(item.endAmount, unitsToFillBn, totalSize).toString(),`

**Comment by xtools-at** [comment]
together with @wooglie we've tested your proposed solution and built a PR from it, thanks for that :) #197
