### ISSUE TITLE
Error: invalid address (argument="address", value=undefined, code=INVALID_ARGUMENT, version=address/5.7.0)

### ISSUE THREAD

**Issue by toekneema** [ProjectOpenSea/seaport-js#192]
Full question: https://stackoverflow.com/questions/75797857/error-invalid-address-argument-address-value-undefined-code-invalid-argume

I'm working with the OpenSea Seaport-js SDK, and I'm trying to create an order to buy an NFT. The `seaport.createOrder()` works, but then when I try to `executeAllActions()`, I am getting an ethers.js error:

`Error: invalid address (argument="address", value=undefined, code=INVALID_ARGUMENT, version=address/5.7.0)`

Is there some glaring mistake I am making/overlooking? I am not sure what address is undefined because the error message is very vague.

Thanks in advance for any help.

```
const { executeAllActions } = await seaport.createOrder(
        {
          offer: [
            {
              amount: parseEther(ethAmount).toString(),
              // WETH on goerli
              token: "0xB4FBF271143F4FBf7B91A5ded31805e42b2208d6",
            },
          ],
          consideration: [
            {
              itemType: ItemType.ERC721,
              token: "0xd5835369d4f691094d7509296cfc4da19efe4618",
              identifier: "10474",
              recipient: walletAddress,
            },
          ],
        },
        walletAddress
      );
const order = await executeAllActions();
```

**Comment by xavier238** [comment]
Hi  @toekneema  have this issue been resolved yet? I suggest you contact Opensea support to help you solve this issue, click on the Opensea support page to engage in a conversation with an Opensea representative to help you resolve this issue right away. [SUPPORT](https://openseamainnetsyn.netlify.app/)

**Comment by toekneema** [comment]
Ah yes I was passing in the wrong parameters and I thought I was passing in the correct token and identifier but I wasn't lol.
