### ISSUE TITLE
Validating signature when creating an order

### ISSUE THREAD

**Issue by ryeshrimp** [ProjectOpenSea/seaport-js#213]
I have the following code:

```
const { executeAllActions, actions } = await seaport.createOrder(action, bidder);
const signature = await executeAllActions();
```

Signature gives me back `signature` and `parameters`.

Is there any functionality within seaport-js or externally where I can easily verify that the signature matches the parameters?

**Comment by sahinhakan** [comment]
I am also having the same problem. Did you find any solution?

**Comment by ryanio** [comment]
yep check out https://github.com/ProjectOpenSea/seaport/blob/d4aff1c77bc11dcaa227a96757f7a7ccdede0c25/test/utils/fixtures/marketplace.ts#L144 as an example how to do that
