### ISSUE TITLE
Delivered via CDN

### ISSUE THREAD

**Issue by ropital** [ProjectOpenSea/seaport-js#233]
The current output js file does not seem to work except in module format on HTML files.

By allowing it to work in formats other than module format, it can be used for a wide range of use cases.

**Comment by ryanio** [comment]
could you give an example of what is not working for you?

**Comment by alxalx14** [comment]
he is having the same issue as me, there isnt really a way provided by the repository to import seaport-js into the html file using <script> tags so it cant be used with a vanilla JS script, instead devs have to use nodejs or so and bring that into the browser. Instructions for getting a JS compatible with script tags in the HTML would be great!

**Comment by ryanio** [comment]
to use in the browser you'll need to use browserify or similar tool to package it properly

**Comment by alxalx14** [comment]
Yeah that makes sense but I think he was suggesting that you guys browserify it for the release version so its easier to do

**Comment by ryanio** [comment]
sure i'll add this for 2.0.1

**Comment by olamicreas** [comment]
> sure i'll add this for 2.0.1

Have you added it?

**Comment by ryanio** [comment]
@olamicreas yes there is a browser build added in every release since 2.0.1

Here is a recent example 
```html
<script src="https://cdn.jsdelivr.net/npm/@opensea/seaport-js@2.0.8/lib/index.min.js"></script>
```

**Comment by olamicreas** [comment]
> @olamicreas yes there is a browser build added in every release since 2.0.1
> 
> Here is a recent example
> 
> ```
> <script src="https://cdn.jsdelivr.net/npm/@opensea/seaport-js@2.0.8/lib/index.min.js"></script>
> ```
Here is the error I got while trying to use the cdn link

"Uncaught ReferenceError: require is not defined
    at index.js:4:19"
