### ISSUE TITLE
All currency tokens in the order must be the same token

### ISSUE THREAD

**Issue by orenyomtov** [ProjectOpenSea/seaport-js#236]
Is [this](https://github.com/ProjectOpenSea/seaport-js/blob/18c6f00191b769eb5f518340e632251becd9f547/src/seaport.ts#L327) a hard limitation of the seaport contracts?
<img width="569" alt="image" src="https://github.com/ProjectOpenSea/seaport-js/assets/168856/de0f6823-f295-40ea-80a7-97e04895d847">

**Comment by sambarnes** [comment]
its not necessarily a hard limitation of the seaport contracts themselves, but rather a restriction imposed by the OpenSea backend (for the sake of making fee calculation & collection simpler)

**Comment by orenyomtov** [comment]
Great! Would you be open to accept a PR that adds a config option to allow for it? (Behavior wouldn't change because it would default to false)

**Comment by sambarnes** [comment]
yep, for sure! ideally we'd like seaport-js to be as flexible as the contracts themselves, only doing such OS-specific validation in the opensea-js repo

for now, your proposal makes sense so that it doesn't break/change for existing users

probs best to requests review from @ryanio and @JoshuaSchmidt-OpenSea, they've been closest to this codebase lately iiuc

**Comment by JoshuaSchmidt-OpenSea** [comment]
@orenyomtov I would not even add a config option. This validation would be done by the OpenSea site/api if a user tried to submit the order to OpenSea. However, there is no reason another marketplace should be required to use the same restriction.

**Comment by orenyomtov** [comment]
Awesome, thanks! I'll get working on it then 🫡

**Comment by orenyomtov** [comment]
Looking for feedback on my PR that addresses this issue: https://github.com/ProjectOpenSea/seaport-js/pull/259

**Comment by ryanio** [comment]
shipped in [v2.0.1](https://github.com/ProjectOpenSea/seaport-js/releases/tag/v2.0.1), thanks @orenyomtov!
