### ISSUE TITLE
fulfillBasicOrder_efficient_6GL6yc gives SERVER ERROR on ethers js using Opensea APIs

### ISSUE THREAD

**Issue by karanpokar** [ProjectOpenSea/seaport-js#238]
Getting this issue when executing fulfillBasicOrder_efficient_6GL6yc. Not sure what else needs to be added.

I am using Alchemy RPC url with Provider created using private key.

Getting this issue while estimating gas. Without estimating, the transaction fails on [blockchain](https://polygonscan.com/tx/0xbe466be4483fa3e8a40f13ed7d1848aa950ee31477bd2fc61c59cc96cdc414cb)

![image](https://github.com/ProjectOpenSea/seaport-js/assets/55875282/9d3fdfd8-5b29-4ded-afd9-36276b8d699a)

Response from OpenSea:

`"function": "fulfillBasicOrder_efficient_6GL6yc((address,uint256,uint256,address,address,address,uint256,uint256,uint8,uint256,uint256,bytes32,uint256,bytes32,bytes32,uint256,(uint256,address)[],bytes))",
Input:
"parameters": {
        "considerationToken": "0x0000000000000000000000000000000000000000",
        "considerationIdentifier": "0",
        "considerationAmount": "23887500000000000",
        "offerer": "0x779e13cc817b2b76f5149763c649b206161d44d1",
        "zone": "0x0000000000000000000000000000000000000000",
        "offerToken": "0x5d666f215a85b87cb042d59662a7ecd2c8cc44e6",
        "offerIdentifier": "11470651",
        "offerAmount": "1",
        "basicOrderType": 0,
        "startTime": "1684816346",
        "endTime": "1700713946",
        "zoneHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
        "salt": "24446860302761739304752683030156737591518664810215442929816394147628551750105",
        "offererConduitKey": "0x0000007b02230091a7ed01230072f7006a004d60a8d4e71d599b8104250f0000",
        "fulfillerConduitKey": "0x0000007b02230091a7ed01230072f7006a004d60a8d4e71d599b8104250f0000",
        "totalOriginalAdditionalRecipients": "1",
        "additionalRecipients": [
          {
            "amount": "612500000000000",
            "recipient": "0x0000a26b00c1f0df003000390027140000faa719"
          }
        ],
        "signature": "0x33f5380b3c21b796f73d820b86b0e8b0d24c50c88ac82adb2dc954f18d51f9409c6cb1fe696962564019620ef11dc4ac0d2f78b17aad37b634557841230c9ff600000613a3080efd934960c4594a03b0d1d65a42a6c36bfcfdf570cf79e310ec144768e71c011c1868b2ec7c39b56262f5439006b3bc749c5192c1b528becd00fd036231ade726cf029bae753ce17dbc86c04aed0d57dd9f1853c94ccf4eca1e23601e0158db89cb2eff365b927f9a142ce1fdd9a41917253fd97e28bbedc8f942be44055cb15be197c6223bcefa3ca7daa19aef2b874e1b740b4b02799a5b768f3cab2335647d7811eb3b8ef1c829d90f0744ac52cd5f012b90a671a458a3c6ea12e1"
      }
    

> }`

**Comment by ryanio** [comment]
You are just sending the parameters, you also need to send the signature, so the order to give to ethers is { parameters, signature }
