### ISSUE TITLE
Update for ethers v6

### ISSUE THREAD

**Issue by oes-varok** [ProjectOpenSea/seaport-js#251]
There's a lot of simple code that raises warnings/errors with the new ethers v6.

The basic example in the readme:

```
const provider = new ethers.providers.Web3Provider(window.ethereum); // old

const provider = new ethers.BrowserProvider(window.ethereum); // new
const seaport = new Seaport(provider); // new BrowserProvider doesn't seem to be accepted?
```

**Comment by ryanio** [comment]
we haven't updated to ethers v6 yet, so please use ethers v5 with this library until we do

**Comment by nick** [comment]
@ryanio [Viem](https://viem.sh/docs/introduction.html) has a significantly smaller bundle size and much better performance. Would you consider accepting a PR moving to Viem?

**Comment by ryanio** [comment]
@nick we will probably stay with ethers as it currently has broader community familiarity and support across developer tools, but if you'd like to create a viem fork that'd be very interesting and by all means please do
