### ISSUE TITLE
Incorrect type signature for `getAdvancedOrderNumeratorDenominator`

### ISSUE THREAD

**Issue by bam4564** [ProjectOpenSea/seaport-js#254]
The following method implementation / type signature have an issue. Code is [here](https://github.com/ProjectOpenSea/seaport-js/blob/763efaf065eec93139e9d810a120df29022fb8bf/src/utils/fulfill.ts#L831) but I've also copy pasted the function in question below. 

```typescript
export const getAdvancedOrderNumeratorDenominator = (
  order: Order,
  unitsToFill?: BigNumberish
) => {
  // Used for advanced order cases
  const maxUnits = getMaximumSizeForOrder(order);
  const unitsToFillBn = BigNumber.from(unitsToFill);

  // Reduce the numerator/denominator as optimization
  const unitsGcd = gcd(unitsToFillBn, maxUnits);

  const numerator = unitsToFill
    ? unitsToFillBn.div(unitsGcd)
    : BigNumber.from(1);
  const denominator = unitsToFill ? maxUnits.div(unitsGcd) : BigNumber.from(1);

  return { numerator, denominator };
};
```

`unitsToFill` can possible be undefined given the type signature but that case is not handled in the code. If the function where to be used that way we would pass undefined to the ethers `BigNumber.from` factory constructor and an error would occur. 

What I believe was the intended behavior here was for `unitsToFillBn` to be set to `maxUnits` in the case where `unitsToFillBn` is not specified. If this was the case, we could make this change 

```typescript
export const getAdvancedOrderNumeratorDenominator = (
  order: Order,
  unitsToFill?: BigNumberish
) => {
  // Used for advanced order cases
  const maxUnits = getMaximumSizeForOrder(order);
  const unitsToFillBn = unitsToFill ? BigNumber.from(unitsToFill) : maxUnits;
  ...
};
```

If this makes sense to everyone I'd be happy to open a PR with the fix.

**Comment by ryanio** [comment]
Thanks for opening, makes sense to me if you'd like to open a PR would be great, please just include a few test cases for coverage / to ensure intended behavior. Probably makes sense to also include a typedoc with the param explanation that when undefined it will be set to the max units available left in the order.

**Comment by bam4564** [comment]
> Thanks for opening, makes sense to me if you'd like to open a PR would be great, please just include a few test cases for coverage / to ensure intended behavior. Probably makes sense to also include a typedoc with the param explanation that when undefined it will be set to the max units available left in the order.

Sounds good, should have some time this week to submit a PR so will tag you once I get that done!

**Comment by bam4564** [comment]
@ryanio quick question here. Right now, there aren't any dedicated tests for utility functions like this. 

Which of these two options would be preferable? 
1. Include the new tests in some existing file related to order fulfillments.  
2. Create a new test file specifically for utility function related to filling?

**Comment by ryanio** [comment]
@bam4564 did you try a `husky install`? If not no worries you can just push with --no-verify flag to skip the hook. Just be sure to run eslint and prettier otherwise ci will trip up (and no worries if you don't get it on your first try can always push a lint fix)

**Comment by ryanio** [comment]
@bam4564 would you still like to open a PR with this fix? it would be much appreciated. otherwise i can do. thanks!
