### ISSUE TITLE
Seaport Doc

### ISSUE THREAD

**Issue by hironate** [ProjectOpenSea/seaport-js#265]
Hey @ryanio 
We are building on top of seaport 1.5 and i really want to contribute to seaport doc. there are lot of things which can be imporved. Do we have any plan for repo for dev docs or any existing repo i can contribute for dev docs ?

**Comment by ryanio** [comment]
Thanks @hironate, we have a docs folder here you can open PRs to suggest improvements: https://github.com/ProjectOpenSea/seaport/tree/main/docs

We also have some docs here: https://docs.opensea.io/reference/seaport-overview - if you would like to help improve these, you can comment in this issue with the suggested changes and I can take a look.

**Comment by hironate** [comment]
@ryanio thanks man. let me improve it.

**Comment by ryanio** [comment]
closing for now, please open a new issue or PR if you have any suggestions for improvements, thanks!
