### ISSUE TITLE
Information -  Upgrade / Migration from Seaport 1.1 to Seaport 1.5

### ISSUE THREAD

**Issue by bruck93** [ProjectOpenSea/seaport-js#281]
Hello,

We're using the Seaport 1.1 and we've waited a bit to migrate to the 1.5 version, but now we've it on our backlog!
Actually our platform have 1.5k listings open in total (but only 12 that are still active since not expired, which should be migrated).

I know that 12 orders are not a massive amount, but which are the best practices to do a bulk listing from a Seaport Version to another one?

I've also read this Tweet from @apiopensea: https://twitter.com/apiopensea/status/1631416150604103681 but the bulk migration is not mentioned.

Thanks!

**Comment by bruck93** [comment]
@ryanio

**Comment by ryanio** [comment]
If you are programmatically creating orders would not recommend bulk listing since it's more expensive to fulfill with the proof, so if it's just 12 listings just list them normally signed with the new 1.5 contract.
