### ISSUE TITLE
English auction orders not fillable by OpenSea

### ISSUE THREAD

**Issue by zackisaacs** [ProjectOpenSea/seaport-js#294]
I am using seaport-js to generate English auctions. The auctions render correctly on OpenSea, but they are never fulfilled by OpenSea; the listing just expires (see [example](https://opensea.io/assets/matic/0xbd001985ca00ef6bb7bc55c7c1e9e09d0d955bf4/22)). I've noticed that the way seaport-js is generating each `createOrder` is slightly different than the OpenSea web UI. Specifically, the `consideration` arrays are different. Here's the consideration generated by my app:

```
          "consideration": [
            {
              "itemType": 1,
              "token": "0x7ceB23fD6bC0adD59E62ac25578270cFf1b9f619",
              "identifierOrCriteria": "0",
              "startAmount": "540000000000000",
              "endAmount": "540000000000000",
              "recipient": "0x8DF847032e94085557125477aAaf1F024FEFA21D"
            },
            {
              "itemType": 1,
              "token": "0x7ceB23fD6bC0adD59E62ac25578270cFf1b9f619",
              "identifierOrCriteria": "0",
              "startAmount": "15000000000000",
              "endAmount": "15000000000000",
              "recipient": "0x0000a26b00c1F0DF003000390027140000fAa719"
            },
            {
              "itemType": 1,
              "token": "0x7ceB23fD6bC0adD59E62ac25578270cFf1b9f619",
              "identifierOrCriteria": "0",
              "startAmount": "45000000000000",
              "endAmount": "45000000000000",
              "recipient": "0x8DF847032e94085557125477aAaf1F024FEFA21D"
            }
          ]
```

And here's the consideration generated by OpenSea:

```
          "consideration": [
            {
              "itemType": 1,
              "token": "0x7ceB23fD6bC0adD59E62ac25578270cFf1b9f619",
              "identifierOrCriteria": "0",
              "startAmount": "540000000000000",
              "endAmount": "540000000000000",
              "recipient": "0x8DF847032e94085557125477aAaf1F024FEFA21D"
            }
          ]
```

Note that these are both for items with a display price of 0.0006 ETH and creator fees of 7.5%, which is why `"startAmount": "540000000000000"`. My app's `createOrder` also includes fees:

```
     fees: [
        {
          recipient: "0x0000a26b00c1f0df003000390027140000faa719", //OpenSea's fees recipient
          basisPoints: 250 //OS receives 2.5% of sales
        },
        {
          recipient: offererAddress, //Creator fees
          basisPoints: 750 //OS receives 2.5% of sales
        }
      ]
```

When I remove these, fulfilling the sell order fails as expected because I'm not supplying OpenSea's required fees:

```
{"errors":["An incorrect OpenSea fee has been provided. Expecting 250 basis points, but received 0."]}
```

It's unclear to me why the consideration arrays are different in these two cases, and it's unclear why OpenSea lists the auction but then never fulfills it. Any help would be much appreciated.

**Comment by ryanio** [comment]
OpenSea will only close the auction if it exceeds 1 eth (so we can recoup tx costs for closing). See [here](https://support.opensea.io/hc/en-us/articles/1500003246082-How-do-timed-auctions-work-):
> Also known as an English auction, OpenSea will automatically complete this transaction if a Sell to highest bidder auction finishes above 1 ETH, with OpenSea paying the gas fee in the process.

The reason why the consideration items are different in the auction order is that it is unclear the final amount that OS would be paid. I believe the "offers"/bids on the auction will have the appropriate consideration items since the bid amount is known and the fees can be calculated from there. Also be sure you are setting the zone to our auction EOA so it has the ability to close it (`0x110b2b128a9ed1be5ef3232d8e4e41640df5c2cd`)

**Comment by zackisaacs** [comment]
Ok, now I understand why this is operating the way it is, but it doesn't make a lot of product sense to me. You set a starting price when you create the auction -- if someone bids that starting price or above, and they're the highest bidder, they should get the item at the end of the auction.

To ask another way, do auctions less than 1 ETH have any value? It seems like the auction might as well not exist because you have to manually accept the highest bid.

If this is just about who pays gas, why not take that out of either the buyer or seller's cut?

**Comment by zackisaacs** [comment]
Also, OpenSea **is** closing out auctions less than 1 ETH when they're created in the OpenSea website. It's just **not** closing out auctions created through the API.

[Example from web creation](https://opensea.io/assets/matic/0xbd001985ca00ef6bb7bc55c7c1e9e09d0d955bf4/8). Note that the sale price was 0.0006 ETH.

[Example from API creation](https://opensea.io/assets/matic/0xbd001985ca00ef6bb7bc55c7c1e9e09d0d955bf4/22).

**Comment by ryanio** [comment]
Closing for now, if you are still experiencing issues creating english auctions on opensea please refer to opensea-js docs for "[Creating English Auctions](https://github.com/ProjectOpenSea/opensea-js#creating-english-auctions)" and [this doc](https://support.opensea.io/hc/en-us/articles/1500003246082-How-do-timed-auctions-work-) as it is more opensea-specific on how we handle auctions rather than seaport-specific.
