### ISSUE TITLE
[docs] add lost param

### ISSUE THREAD

**Issue by TrejGun** [ProjectOpenSea/seaport-js#30]
the readme states that the Seaport object can be initialized with only one parameter

https://github.com/ProjectOpenSea/seaport-js/blob/main/README.md?plain=1#L34

but typescript types require two parameters

https://github.com/ProjectOpenSea/seaport-js/blob/main/src/seaport.ts#L83

one of these should be fixed and I can create a PR but I do not know which one is correct
seems like adding question mark in typings will solve the issue

**Comment by sunwrobert** [comment]
Fixing this in #38
