### ISSUE TITLE
seaport-js v3 planning

### ISSUE THREAD

**Issue by ryanio** [ProjectOpenSea/seaport-js#301]
## Breaking changes

- [x] Upgrade to ethers v6 (related issue: #251)
  - [x] Upgrade JS target version to use native BigInt
  - [x] Batching seems to be automatically included in ethers v6 (see [JsonRpcApiProviderOptions](https://docs.ethers.org/v6/api/providers/jsonrpc/#JsonRpcApiProviderOptions)), so `@0xsequence/multicall` dependency can be removed

## Non-breaking changes (applicable for inclusion in patch or minor releases)

- [ ] (placeholder)

**Comment by jxom** [comment]
Would be cool to see viem support too! Willing to offer any assistance or guidance if you would consider it. 🙏
