### ISSUE TITLE
[bug] bulkCancelOrders is broken

### ISSUE THREAD

**Issue by TrejGun** [ProjectOpenSea/seaport-js#34]
calling 

```
seaport.bulkCancelOrders()
```

results in error

<img width="819" alt="Screen Shot 2022-06-07 at 08 46 14" src="https://user-images.githubusercontent.com/185285/172272356-0c78bec0-e7db-4ba2-b2b4-087ff45ce5bf.png">

because of improper type conversion

[here](https://github.com/ProjectOpenSea/seaport-js/blob/1f285ec3594446f5fb1754bed0bd056037b812fd/src/seaport.ts#L401 ) 
an empty array is passed 

[here](https://github.com/ProjectOpenSea/seaport-js/blob/1f285ec3594446f5fb1754bed0bd056037b812fd/src/utils/usecase.ts#L60) last item of this empty array is taken which is undefined

and [here](https://github.com/ProjectOpenSea/seaport-js/blob/1f285ec3594446f5fb1754bed0bd056037b812fd/src/utils/usecase.ts#L49) this undefined is passed to Object.keys which can accept an only object.

I can create PR with a fix. just tell me if defaulting `obj` to `{}` in `instanceOfOverrides` would be appropriate

**Comment by sunwrobert** [comment]
Closing as fixed
