### ISSUE TITLE
Creating a collection offer returns error

### ISSUE THREAD

**Issue by cnolden90** [ProjectOpenSea/seaport-js#375]
### Component

API

### Have you ensured that all of these are up to date?

- [X] seaport-js
- [ ] Node (minimum v16)

### What version of seaport-js are you on?

1.3.0

### What function is the bug in?

createOrder

### Operating System

Linux

### Describe the bug

Hello everyone,

over the past year I used the `seaport.creatOrder() ` in order to create a collection offer. The code is as following:
```

const { actions } = await seaport.createOrder(
        {
            allowPartialFills: false,
            restrictedByZone: true,
            offer: [{
                amount: priceNew,
                token: ethContractAddress,
            }],
            consideration: [{
                itemType: collectionOfferBuild.itemType,
                token: collectionOfferBuild.token,
                identifier: collectionOfferBuild.identifierOrCriteria,
                recipient: collectionOfferBuild.recipient,
            }],
            fees: feeArray,
            orderType: 0,
            "startTime": Math.round(Date.now() / 1000),
            "endTime": Math.round(Date.now() / 1000 + 60 * 60 * hours),
            "zone": zoneParameter,
            "conduitKey": conduitKey,
            "protocol_address": "0x00000000000000adc04c56bf30ac9d3c0aaf14dc"
        },
        offererAddress);
    const createOrderAction = actions[0];
```

Since mid last week I receive that:

`[
  'You have attempted to create a order, but you provided an offer item or consideration item with a 0 start amount. Remove this 0-amount item if this was intended.'
]
`
I haven't changed anything, can you advise me how to fix that? I think it's a bug. Discord manager asked me to create the ticket here.

**Comment by ryanio** [comment]
Can you please try with the latest seaport-js version?

The consideration item needs an "amount" too, can you try setting it to 1.

**Comment by cnolden90** [comment]
I installed latest seaport version.(2.0.7) I also added `amount = 1 ` into the consideration and still get the same error.

**Comment by noldenc** [comment]
Update @ryanio ?

**Comment by ryanio** [comment]
i can't help much further without an independent code snippet to replicate the error, are sure `priceNew` isn't 0?

**Comment by cnolden90** [comment]
The issue still remains. priceNew is not 0. 

`async function createCollectionOffer(collectionOfferBuild, slug, seaport, contract, offererAddress, ownWethAmount, feeArray, hours, chain, ethContractAddress, retryAmount, zoneParameter) {
    let chainConverted = null;
    let zone = "0x";
    let conduitKey = "0x";
    let zoneHash = "0x";
    if (chain == 1) {
        zone = zoneParameter;
        conduitKey = "0x0000007b02230091a7ed01230072f7006a004d60a8d4e71d599b8104250f0000";
        chainConverted = "ethereum";
    } else {
        zone = zoneParameter;
        conduitKey = "0x0000007b02230091a7ed01230072f7006a004d60a8d4e71d599b8104250f0000";
        chainConverted = "matic";
    }
    let priceNew = ethers.utils.parseEther(ownWethAmount.toString()).toString();
    const { actions } = await seaport.createOrder(
        {
            allowPartialFills: false,
            restrictedByZone: true,
            offer: [{
                amount: priceNew,
                token: ethContractAddress,
            }],
            consideration: [{
                itemType: collectionOfferBuild.itemType,
                token: collectionOfferBuild.token,
                identifier: collectionOfferBuild.identifierOrCriteria,
                recipient: collectionOfferBuild.recipient,
                amount: 1
            }],
            fees: feeArray,
            orderType: 0,
            "startTime": Math.round(Date.now() / 1000),
            "endTime": Math.round(Date.now() / 1000 + 60 * 60 * hours),
            "zone": zoneParameter,
            "conduitKey": conduitKey,
            "protocol_address": "0x00000000000000adc04c56bf30ac9d3c0aaf14dc"
        },
        offererAddress);
    const createOrderAction = actions[0];
    const message = await createOrderAction.getMessageToSign();
    const order = await createOrderAction.createOrder();
    if (!order) {
        console.log("Failure creating order.");
        return;
    }
    const payload = {
        "criteria": {
            "collection": {
                "slug": slug
            }
        },
        "protocol_data": {
            "parameters": order.parameters,
            "signature": order.signature
        },
        protocol_address: "0x00000000000000ADc04C56Bf30aC9d3c0aAF14dC"
    }
    let tryNumber = 0;
    let exit = false;
    do {
        if (tryNumber < retryAmount) {
            tryNumber = tryNumber + 1;
            const offerMade = await submitCollectionOfferToOpenSea(payload, chain);
            await delay(500);
            if (offerMade.status == 200) {
                exit = true;
                console.log(`==== ${ownWethAmount} WETH Offer is made on collection: https://opensea.io/collection/${slug} ====`);
            }
            else {
                if (offerMade.status == 429) {
                    console.log("\u001B[5m" + `!!!! Something went wrong with the collection offer for collection: https://opensea.io/collection/${slug}! Retrying.... \u001B[0m`);
                }
                else {
                    const checkErrors = await offerMade.json();
                    if (("errors" in checkErrors) == true) {
                        exit = true;
                        console.log(checkErrors.errors);
                    } else {
                        console.log("\u001B[5m" + `!!!! Something went wrong with the collection offer for collection: https://opensea.io/collection/${slug}! Retrying.... \u001B[0m`);
                    }
                }
            }
        }
        else {
            exit = true;
        }
    }
    while (exit == false)
}`
