### ISSUE TITLE
Inaccurate Tip Adjustment in Partial Fill Scenarios in Seaport SDK

### ISSUE THREAD

**Issue by sofianeOuafir** [ProjectOpenSea/seaport-js#423]
### Component

Utils

### Have you ensured that all of these are up to date?

- [X] seaport-js
- [X] Node (minimum v16)

### What version of seaport-js are you on?

v2.0.8

### What function is the bug in?

fulfillStandardOrder

### Operating System

macOS (Apple Silicon)

## Description

The Seaport SDK currently has an issue with incorrect tip adjustment in partial fill scenarios, leading to discrepancies in expected versus actual tip amounts. This affects the reliability of transaction handling.

## Reproduction Scenario

**Initial Setup:** An order to sell 10 editions of an ERC1155 NFT, each at 1 ETH, with a 1 ETH tip.
**Partial Fulfillment:** A buyer purchases 3 editions, expecting to be charged 3.3 ETH (3 ETH for NFTs + 0.3 ETH adjusted tip).
**Actual Behavior:** The SDK charges 4 ETH due to unadjusted tip calculation.
**Impact:** This leads to unnecessary overpayments and refunds, affecting user experience and transaction predictability.

## Proposed Solution and PR

An adjustTipsForPartialFills function is proposed to correct this issue. This is addressed in PR [#416](https://github.com/ProjectOpenSea/seaport-js/pull/416), which aims to ensure accurate tip calculations in partial fill scenarios.

**Comment by Sufiyan-dev** [comment]
hey @sofianeOuafir, 
I have a question about the tip splitting. if the use purchase 3 editions and if we split the 1 ETH in 3 of them, which will be 1 / 3 = 0.34. I think rounding up might be a solution.

**Comment by sofianeOuafir** [comment]
Hey @Sufiyan-dev, I have a solution that works in #413

**Comment by ryanio** [comment]
Fixed and released in [v3.0.1](https://github.com/ProjectOpenSea/seaport-js/releases/tag/v3.0.1)
