### ISSUE TITLE
Support Node >=v14

### ISSUE THREAD

**Issue by stewart-prysm** [ProjectOpenSea/seaport-js#43]
Most apps that will use `seaport-js` will be webapp clients. It doesn't make sense to enforce the latest node version when node is not used on the client.

I'm requesting that you downgrade the seaport-js node requirement to 14, ie `>=v14.19.1` or just remove this restriction altogether.

The reason I'm asking is because I'm up-taking seaport on my client app which is served by a Node 14 server-- it's turning out to be a challenging upgrade. Since the seaport protocol was just released, it is time sensitive for my app to upgrade before you disable wyvern.

Thanks.

**Comment by plondon** [comment]
We're also in the process of integrating seaport for https://github.com/blockchain/blockchain-wallet-v4-frontend and would also prefer >= node 14.

**Comment by sunwrobert** [comment]
Published 1.0.2

**Comment by stewart-prysm** [comment]
@sunwrobert Thanks!
