### ISSUE TITLE
POST /v2/orders/: canceling statement due to statement timeout

### ISSUE THREAD

**Issue by plondon** [ProjectOpenSea/seaport-js#47]
Hello OpenSea team!

I am trying to post a seaport order to the new v2 endpoint.

URL: https://api.opensea.io/v2/orders/ethereum/seaport/offers

Data:
> {"parameters":{"offerer":"0x2a47583d9604E25f4e1AadF323f8701bB93Cad33","zone":"0x004c00500000ad104d7dbd00e3ae0a5c00560c00","zoneHash":"0x3000000000000000000000000000000000000000000000000000000000000000","startTime":"1655499967","endTime":"1655586366","orderType":2,"offer":[{"itemType":1,"token":"0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2","identifierOrCriteria":"0","startAmount":"10000000000000000","endAmount":"10000000000000000"}],"consideration":[{"itemType":2,"token":"0x9c8ff314c9bc7f6e59a9d9225fb22946427edc03","identifierOrCriteria":"0","startAmount":"1","endAmount":"1","recipient":"0x2a47583d9604E25f4e1AadF323f8701bB93Cad33"},{"itemType":1,"token":"0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2","identifierOrCriteria":"0","startAmount":"250000000000000","endAmount":"250000000000000","recipient":"0x8de9c5a032463c561423387a9648c5c7bcc5bc90"}],"totalOriginalConsiderationItems":2,"salt":"0xce3dd639ae780510e18108a332850e40","conduitKey":"0x0000007b02230091a7ed01230072f7006a004d60a8d4e71d599b8104250f0000","counter":0},"signature":"0xb5...d992"}

Error: `errors: [ 'canceling statement due to statement timeout\n' ]`

I have successfully fixed the previous errors:

1. `errors: [ 'Invalid order signature' ]`
2. `errors: [
    'You provided an invalid order type: OrderType.FULL_OPEN, please set it to be FULL_RESTRICTED or PARTIAL_RESTRICTED'
  ]`

**Comment by sunwrobert** [comment]
Please direct these to `opensea-js`
