### ISSUE TITLE
Use ethers.Signer abstract class instead of providers.JsonRpcProvider

### ISSUE THREAD

**Issue by stewart-prysm** [ProjectOpenSea/seaport-js#48]
Requesting you change the Seaport `provider` constructor argument to the abstract class `ethers.Signer`. This would give developers much more flexibility in using this library. For example I could inject the gnosis safe adapter https://www.npmjs.com/package/@gnosis.pm/safe-ethers-adapters?activeTab=readme to easily interop with gnosis safe.

**Comment by sunwrobert** [comment]
@stewart-prysm just for my learning, is `signer.provider` going to be populated for your gnosis safe example?

**Comment by Trontor** [comment]
@stewart-prysm in need of this - were you able to do this yourself easily?

**Comment by sunwrobert** [comment]
Opened a PR to fix this, let me know if this works for you

**Comment by stewart-prysm** [comment]
@sunwrobert Sorry for the late response. Yes this is working for me. I had to make a slight modification that I will create another ticket for.

For those running into issues with smart contract wallets-- pass in a custom ethers signer to the seaport-js constructor that contains your smart contract wallet address, but override all sign methods to return a fake but valid signature. This is necessary when creating orders with `@opensea/seaport-js` because the sdk automatically requests a typed signature and parses the signature. Luckily it does not check for signature validity which would break this workaround.
