### ISSUE TITLE
Example in the Readme

### ISSUE THREAD

**Issue by pguardiario** [ProjectOpenSea/seaport-js#51]
Is it correct that opensea.js will be deprecated in the future in favor of this one? If so it would be great to have examples like opensea.js has of things like fulfilling sell orders. Also was there a decision to move from web3 to ethers, or will this also support web3?

**Comment by sunwrobert** [comment]
opensea-js is not going to be deprecated. This is a library agnostic of OpenSea, and is solely used to interface with the Seaport contract.

**Comment by pguardiario** [comment]
Thanks @sunwrobert,

I'm having trouble understanding the seaport marketing-speak. According to opensea:

OpenSea is migrating to [Seaport](https://opensea.io/blog/announcements/introducing-seaport-protocol/), a new web3 marketplace protocol designed for safely and efficiently buying and selling NFTs. Seaport is a game changer – it’s open source, inherently decentralized, and a modern foundation that will help us (and any teams using it) build and release new features more quickly

Can you explain what exactly they mean by "OpenSea is migrating to Seaport" and how that is different from  deprecating the old library?

**Comment by sunwrobert** [comment]
opensea-js uses this library, seaport-js to post orders and do Opensea specific validation. does that make sense?

This library has no relation to OpenSea itself. It's just a way to interact with the contract. opensea-js deals with OpenSea specific stuff and uses this library under the hood to actually fulfill orders.

**Comment by pguardiario** [comment]
Thanks @sunwrobert,
Sorry it's not really clear to me yet.

Let's say for example I want to let users fulfill an opensea sell order from my website.
Should I choose seaport-js or opensea-js and what would the difference be?

**Comment by sunwrobert** [comment]
use opensea-js

**Comment by pguardiario** [comment]
Ok noted. So who exactly should care about seaport.js outside of the opensea team?

**Comment by sunwrobert** [comment]
@pguardiario anyone who wants to create their own marketplace using the Seaport exchange. It doesn't have to be OpenSea, anyone can set up a frontend to interact with the exchange.

**Comment by pguardiario** [comment]
So it can interact with an exchange but it can't fulfill sell orders? What exactly do you mean by "the Seaport exchange"? Do you mean the contracts?

**Comment by sunwrobert** [comment]
It can fulfill sell orders if you pass in the Consideration struct that's on the sell order. Seaport exchange is a contract.

**Comment by MetalGear-cmd** [comment]
It will be really helpful to have working examples of the seaport protocol like we see in the Opensea-js SDK, since this is being used under the hood to fulfillOrders and other functions.

**Comment by sunwrobert** [comment]
Yup, I'll get an example this week hopefully

**Comment by sunwrobert** [comment]
@pguardiario @MetalGear-cmd I added an example here: https://github.com/ProjectOpenSea/seaport-js/pull/57

You can also look at the test files to get a better idea.

**Comment by MetalGear-cmd** [comment]
@jtaaa Thanks for adding the examples, is there any example of fulfillAvailableOrders()?

**Comment by pguardiario** [comment]
This doesn't actually address the issue of providing example code to fulfill an arbitrary sell order. Please reopen, and I would love to hear from someone on the seaport team who can provide this, thanks.
