### ISSUE TITLE
eth_signTypedData_v4 issue while trying createOrder() from non-browser providers.

### ISSUE THREAD

**Issue by Racherin** [ProjectOpenSea/seaport-js#52]
Hey, there was an error about signing data after migrating to opensea-js V 2.0.0 based on issue https://github.com/ProjectOpenSea/opensea-js/issues/372 .

I'm facing with same issue again after trying to use opensea-js 4.0.1 version to createOrder with hdwallet-provider . 
Anyway, all the functions about signing data moved to seaport-js.

```shell
/node_modules/@truffle/hdwallet-provider/node_modules/eth-sig-util/dist/index.js:172
        if (results.includes(primaryType) || types[primaryType] === undefined) {
                                                  ^
TypeError: Cannot read properties of undefined (reading 'EIP712Domain')
```

On opensea-js that issue solved by creating a catch block to handle eth_signTypedData_v4 errors and use it eth_signTypedData instead of it, but I can see that web3.js is no longer used in seaport-js.

```javascript
export async function signTypedDataAsync(
  web3: Web3,
  message: object,
  signerAddress: string
): Promise<ECSignature> {
  let signature: JsonRpcResponse | undefined;
  try {
    // Using sign typed data V4 works with a stringified message, used by browser providers i.e. Metamask
    signature = await promisify<JsonRpcResponse | undefined>((c) =>
      (web3.currentProvider as AbstractProvider).sendAsync(
        {
          method: "eth_signTypedData_v4",
          params: [signerAddress, JSON.stringify(message)],
          from: signerAddress,
          id: new Date().getTime(),
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
        } as any,
        c
      )
    );
  } catch {
    // Fallback to normal sign typed data for node providers, without using stringified message
    // https://github.com/coinbase/coinbase-wallet-sdk/issues/60
    signature = await promisify<JsonRpcResponse | undefined>((c) =>
      (web3.currentProvider as AbstractProvider).sendAsync(
        {
          method: "eth_signTypedData",
          params: [signerAddress, message],
          from: signerAddress,
          id: new Date().getTime(),
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
        } as any,
        c
      )
    );
  }
```

When I check code, can see same signing method but it's handled by ethers.js and there's no support for eth_signTypedData.

https://github.com/ProjectOpenSea/seaport-js/blob/3d789593e54594acfeef88e83bb0b3a4c1570af9/src/seaport.ts#L344-L366

I'm sure this will be big problem after v1/orders endpoint deprecated. Many developers use node providers to bid faster.

**Comment by nextmove** [comment]
I am also getting this error when I run createBuyOrder with 4.0.0-beta.2 and @truffle/hdwallet-provider.

**Comment by sunwrobert** [comment]
I'll take a look at this.

**Comment by nextmove** [comment]
After implemented the fix, I'm getting "Account not found" message.

**Comment by sunwrobert** [comment]
@nextmove is that on the `signer.getAddress()` call? Do you have a repro

**Comment by Racherin** [comment]
@sunwrobert your commit throws 

```shell
[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "Account not found".] {
  code: 'ERR_UNHANDLED_REJECTION'
}
```

**Comment by ahmetcanerkilavuz** [comment]
@sunwrobert same error

**Comment by sunwrobert** [comment]
it sounds like a fundamental problem with using signTypedData v1 where it can't encode arrays properly. I'm not sure we can fix this then. Can node providers instead just support v4?

**Comment by Racherin** [comment]
Before seaport protocol, this function could work at least while API is not disabled. now OpenSea devs switched to use ethers API instead of web3 and this error just happened. 

Most developers does programmatic orders through node providers. There are lots of complain about this on the discord channel, I think wyvern orders should continue to work until this is fixed. @alexanderatallah

**Comment by sunwrobert** [comment]
Closing this, as this is fixed in [Truffle 5.5.20](https://github.com/trufflesuite/truffle/releases/tag/v5.5.20)

**Comment by hironate** [comment]
@sunwrobert is this issue fixed, as this is not working with mobile wallets and getting same error. As mobile wallet (for e.g) doesn't support eth_signTypedData_v4, you need to use personal_sign. i could sign message separately but createOrder function calls _formatOrder function which private, so no way to build OrderComponents using seaport.js

FYI i am trying to do this using wallet connect.

**Comment by ryanio** [comment]
@hironate Seaport only works with signTypedData v4, personal_sign is a different (outdated/insecure) standard.

**Comment by cg-yamada** [comment]
@ryanio 
Hi, I am developing a dApp using `seaport-js` and `web3modal (v2)`.
Am I correct that the `createOrder` method is impossible to work with mobile metamask?

**Comment by hironate** [comment]
@ryanio trust wallet doesn;t support signTypedDataV4, not sure how opensea does that, it works on their end with trust wallet. are they using personal_sign by manually building orders ?
