### ISSUE TITLE
Getting Started

### ISSUE THREAD

**Issue by gregorym** [ProjectOpenSea/seaport-js#54]
Let's say I wanted to build a new marketplace using seaport and seaport-js. Would I need to deploy my own version of the seaport contract or i would rely on the existing one? If I rely on the existing one, would that mean opensea get the 2.5% commission?

It a little unclear if opensea is 100% decoupled from seaport or where the opensea business logic lives.

**Comment by sunwrobert** [comment]
Rely on the existing one. No OpenSea wouldn't get any commision (fees are set in the `consideration` of the order. On OpenSea, we set an OS fee `consideration` when users create an order, but your own marketplace wouldn't need to set that `consideration` item. OpenSea is 100% decoupled from Seaport.

Closing unless there is more confusion here.
