### ISSUE TITLE
Error: Invalid order signature

### ISSUE THREAD

**Issue by gqoew** [ProjectOpenSea/seaport-js#55]
I am manually building and signing an EIP-712 message corresponding to a seaport listing order using the order components (to be precise I am not using `seaport-js` to do this).

Once signed, I call the create order [API endpoint for `RINKEBY` network](https://docs.opensea.io/v2.0/reference/create-an-order-testnets) and provide the order components + the  EIP-712 signature.

I get the following error: `'Invalid order signature'`

Could you give me some precisions on:

- What format / types do you expect for the EIP-712 message? Can you give an example?
- What format / types do you expect for the API  params `parameters` and `signature`? Can you give an example?
- How the API backend verifying the signature? Do you expect a classic EIP-712 signature string?

**Comment by sunwrobert** [comment]
We validate the signature by just passing into the `validate` static call on the seaport contract. 

Not sure what you mean by what format/types you expect for the EIP-712 message.

**Comment by jack75015** [comment]
which signer / lib did you use to sign the message?

**Comment by gqoew** [comment]
@jack75015

The signer is the same wallet as the offerer of the order signed.
I am using python's lib `eth_account`. Unfortunately it does not seem to provide EIP-2098 signatures.

**Comment by gqoew** [comment]
> From what I see here: https://github.com/ProjectOpenSea/seaport/blob/a62c2f8f484784735025d7b03ccb37865bc39e5a/reference/lib/ReferenceSignatureVerification.sol#L32
> 
> It seems EIP-2098 signatures and "standard" signatures of byte length `65` are accepted. I think my signature is "standard" (a `0x...` string of character length 132 for the API or a byte object of length `65` for the `validate` function).
> 
> When I sign the EIP-712 message and recover on my side, it confirms the offerer and the signer addresses are identical.
> 
> @sunwrobert I tried to call `validate` directly with an `Order[]` object and I got an error. This error is probably what causes the API response `Error: Invalid order signature`.
> 
> Maybe the input data I am sending to the API / `validate` function - once encoded by your backend - differs from the data I have actually signed?

It seems it could be an encoding issue on  `eth_account` side: https://github.com/ethereum/eth-account/issues/174. I'll try out their patches and re-open the issue if their patch don't fix the issue.

**Comment by kaifeitudou** [comment]
@gqoew I also have the same error 'Invalid order signature' when use python to create an offer  on opensea. Can you give me an example? thanks very much
