### ISSUE TITLE
Cannot Buy NFT

### ISSUE THREAD

**Issue by karanpokar** [ProjectOpenSea/seaport-js#586]
### Component

Utils

### Have you ensured that all of these are up to date?

- [X] seaport-js
- [x] Node (minimum v16)

### What version of seaport-js are you on?

2.0.8

### What function is the bug in?

fulfillOrders

### Operating System

macOS (Apple Silicon)

### Describe the bug

```
 await seaport.fulfillOrders({fulfillOrderDetails:orderData,accountAddress:fulfiller});
  const transaction = await executeAllFulfillActions();
```

Transaction Getting Reverted

Error: cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (error={"reason":"execution reverted","code":"UNPREDICTABLE_GAS_LIMIT","method":"estimateGas","transaction":{"from":"0x3727b8ba841e40A5F0B82105eB3f760Ad4854fDB","maxPriorityFeePerGas":{"type":"BigNumber","hex":"0x59682f00"},"maxFeePerGas":{"type":"BigNumber","hex":"0x01749e9eac"},"to":"0x00000000000000ADc04C56Bf30aC9d3c0aAF14dC","value":{"type":"BigNumber","hex":"0x6a94d74f430000"},"data":"0x87201b4100000000000000000000000000000000000000000000000000000000000000e000000000000000000000000000000000000000000000000000000000000006c000000000000000000000000000000000000000000000000000000000000006e000000000000000000000000000000000000000000000000000000000000007800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000a00000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000005200000000000000000000000000000000000000000000000000000000000000580000000000000000000000000dee50031e7129b7d6c9dccc6017ca438c2c1e31a0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000016000000000000000000000000000000000000000000000000000000000000002200000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000006645b29a000000000000000000000000000000000000000000000000000000006738549f0000000000000000000000000000000000000000000000000000000000000000360c6ebe00000000000000000000000000000000000000006641fc1d714f3c190000007b02230091a7ed01230072f7006a004d60a8d4e71d599b8104250f0000000000000000000000000000000000000000000000000000000000000000000300000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000002000000000000000000000000caa992609587956f2e397033a1a6d217c4d8e5e200000000000000000000000000000000000000000000000000000000000005d40000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000030000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000067e7fdd5bef0000000000000000000000000000000000000000000000000000067e7fdd5bef000000000000000000000000000dee50031e7129b7d6c9dccc6017ca438c2c1e31a0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002aa1efb94e0000000000000000000000000000000000000000000000000000002aa1efb94e0000000000000000000000000000000a26b00c1f0df003000390027140000faa719000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002ba7def3000000000000000000000000000000000000000000000000000000002ba7def3000000000000000000000000000e86d914efd8370c468b942bf2bff52463197edba00000000000000000000000000000000000000000000000000000000000000403b234c70c12c856398a68dbc43a9c4993c69ff5dcf60c4f11c0c4539b7dedaa26ad4eac56c746147d71516b1a10375a03a5be4e63b6828f24c81cfccd3ec576100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000003000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000c00000000000000000000000000000000000000000000000000000000000000120000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002","type":2,"accessList":null},"error":{"reason":"processing response error","code":"SERVER_ERROR","body":"{\"id\":54,\"jsonrpc\":\"2.0\",\"error\":{\"code\":3,\"message\":\"execution reverted\",\"data\":\"0x815e1d64\"}}","error":{"code":3,"data":"0x815e1d64"},"requestBody":"{\"method\":\"eth_estimateGas\",\"params\":[{\"type\":\"0x2\",\"maxFeePerGas\":\"0x1749e9eac\",\"maxPriorityFeePerGas\":\"0x59682f00\",\"value\":\"0x6a94d74f430000\",\"from\":\"0x3727b8ba841e40a5f0b82105eb3f760ad4854fdb\",\"to\":\"0x00000000000000adc04c56bf30ac9d3c0aaf14dc\",\"data\":\"0x87201b4100000000000000000000000000000000000000000000000000000000000000e000000000000000000000000000000000000000000000000000000000000006c000000000000000000000000000000000000000000000000000000000000006e000000000000000000000000000000000000000000000000000000000000007800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000a00000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000005200000000000000000000000000000000000000000000000000000000000000580000000000000000000000000dee50031e7129b7d6c9dccc6017ca438c2c1e31a0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000016000000000000000000000000000000000000000000000000000000000000002200000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000006645b29a000000000000000000000000000000000000000000000000000000006738549f0000000000000000000000000000000000000000000000000000000000000000360c6ebe00000000000000000000000000000000000000006641fc1d714f3c190000007b02230091a7ed01230072f7006a004d60a8d4e71d599b8104250f0000000000000000000000000000000000000000000000000000000000000000000300000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000002000000000000000000000000caa992609587956f2e397033a1a6d217c4d8e5e200000000000000000000000000000000000000000000000000000000000005d40000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000030000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000067e7fdd5bef0000000000000000000000000000000000000000000000000000067e7fdd5bef000000000000000000000000000dee50031e7129b7d6c9dccc6017ca438c2c1e31a0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002aa1efb94e0000000000000000000000000000000000000000000000000000002aa1efb94e0000000000000000000000000000000a26b00c1f0df003000390027140000faa719000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002ba7def3000000000000000000000000000000000000000000000000000000002ba7def3000000000000000000000000000e86d914efd8370c468b942bf2bff52463197edba00000000000000000000000000000000000000000000000000000000000000403b234c70c12c856398a68dbc43a9c4993c69ff5dcf60c4f11c0c4539b7dedaa26ad4eac56c746147d71516b1a10375a03a5be4e63b6828f24c81cfccd3ec576100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000003000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000c00000000000000000000000000000000000000000000000000000000000000120000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002\"}],\"id\":54,\"jsonrpc\":\"2.0\"}","requestMethod":"POST","url":"https://polygon-rpc.com"}}, tx={"data":"0x87201b4100000000000000000000000000000000000000000000000000000000000000e000000000000000000000000000000000000000000000000000000000000006c000000000000000000000000000000000000000000000000000000000000006e000000000000000000000000000000000000000000000000000000000000007800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000a00000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000005200000000000000000000000000000000000000000000000000000000000000580000000000000000000000000dee50031e7129b7d6c9dccc6017ca438c2c1e31a0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000016000000000000000000000000000000000000000000000000000000000000002200000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000006645b29a000000000000000000000000000000000000000000000000000000006738549f0000000000000000000000000000000000000000000000000000000000000000360c6ebe00000000000000000000000000000000000000006641fc1d714f3c190000007b02230091a7ed01230072f7006a004d60a8d4e71d599b8104250f0000000000000000000000000000000000000000000000000000000000000000000300000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000002000000000000000000000000caa992609587956f2e397033a1a6d217c4d8e5e200000000000000000000000000000000000000000000000000000000000005d40000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000030000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000067e7fdd5bef0000000000000000000000000000000000000000000000000000067e7fdd5bef000000000000000000000000000dee50031e7129b7d6c9dccc6017ca438c2c1e31a0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002aa1efb94e0000000000000000000000000000000000000000000000000000002aa1efb94e0000000000000000000000000000000a26b00c1f0df003000390027140000faa719000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002ba7def3000000000000000000000000000000000000000000000000000000002ba7def3000000000000000000000000000e86d914efd8370c468b942bf2bff52463197edba00000000000000000000000000000000000000000000000000000000000000403b234c70c12c856398a68dbc43a9c4993c69ff5dcf60c4f11c0c4539b7dedaa26ad4eac56c746147d71516b1a10375a03a5be4e63b6828f24c81cfccd3ec576100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000003000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000c00000000000000000000000000000000000000000000000000000000000000120000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002","to":{},"from":"0x3727b8ba841e40A5F0B82105eB3f760Ad4854fDB","value":{"type":"BigNumber","hex":"0x6a94d74f430000"},"type":2,"maxFeePerGas":{"type":"BigNumber","hex":"0x01749e9eac"},"maxPriorityFeePerGas":{"type":"BigNumber","hex":"0x59682f00"},"nonce":{},"gasLimit":{},"chainId":{}}, code=UNPREDICTABLE_GAS_LIMIT, version=abstract-signer/5.7.0)

**Comment by ryanio** [comment]
this means the transaction will fail, you should set an explicit gas limit and see what the returned error code is, if it's a 4 byte code you can query it here: https://openchain.xyz/signatures

actually i see it in the middle of yours: `0x815e1d64`
that is:
`InvalidSigner()` meaning the signature does not match the order offerer

**Comment by karanpokar** [comment]
I am using ethers 5.7 and passing the signer generated from 
const signer = new ethers.Wallet(PK, provider);
Am I doing it wrong?

**Comment by dhavalmp194** [comment]
is it resolved?
I am facing error in buying NFT which is below : 
Error: The fulfiller does not have the balances needed to fulfill.

can anyone please guide me.

**Comment by dhavalmp194** [comment]
@ryanio
