### ISSUE TITLE
Default provider confusion from the documentation

### ISSUE THREAD

**Issue by KatFishSnake** [ProjectOpenSea/seaport-js#70]
👋 Hey guys,

I am trying to figure out how to use this library instead of the opensea-js mostly of this library support of bulk purchasing of tokens.

No matter how I try to figure out what providers to use nothing works and documentation suggests to use

```typescript
const provider = ethers.getDefaultProvider();
```

Which is seemingly incorrect and doesn't work out of the box, as the library works only with `JsonRpcProvider` and `getDefaultProvider` exports `BaseProvider` that is missing `getSigner` method.

https://github.com/ProjectOpenSea/seaport-js/blob/5952c3cf162c7ab657a0ec455140df9a7f62ee60/src/seaport.ts#L67-L69

So trying to understand if I am doing something that I am not supposed to do, or we should really update the docs with more relevant example.

Thanks.

**Comment by sunwrobert** [comment]
I think we should update the docs in this case. I'll take a look at this

**Comment by sunwrobert** [comment]
Opened a PR to fix this, let me know if this works for you

**Comment by KatFishSnake** [comment]
@sunwrobert 🙏 thank you for the fix, if you have some more time, created another issue / suggestion
https://github.com/ProjectOpenSea/seaport-js/issues/73
