### ISSUE TITLE
Confusion with createOrder params

### ISSUE THREAD

**Issue by KatFishSnake** [ProjectOpenSea/seaport-js#73]
Hey 👋,

the portion of documentation for making orders is a little confusing 

https://github.com/ProjectOpenSea/seaport-js/blob/main/README.md#making-an-offer-for-an-erc-721-for-10-weth-and-fulfilling-it

The params seem to be incorrect, for example the docs suggest us to use `createOrder` like so, this simply does work

```typescript
const { executeAllActions } = await seaport.createOrder({
  offer: [
    {
      amount: parseEther("10").toString(),
      // WETH
      token: "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2",
    },
  ],
  consideration: [
    {
      itemType: ItemType.ERC721,
      token: "0x8a90cab2b38dba80c64b7734e58ee1db38b8992e",
      identifier: "1",
      recipient: offerer,
    },
  ],
  accountAddress: offerer,
});
```

and needs to be rewritten as 
```typescript 
const { executeAllActions } = await seaport.createOrder(
  {
    offer: [
      {
        itemType: ItemType.ERC721,
        token: "0x8a90cab2b38dba80c64b7734e58ee1db38b8992e",
        identifier: "1",
      },
    ],
    consideration: [
      {
        amount: parseEther("10").toString(),
        recipient: offerer,
      },
    ],
  },
  offerer
);
```

Am I understanding this correctly? Can we update the documentation to be a bit clearer on what is expected?

**Comment by sunwrobert** [comment]
Good point, mind submitting a PR to fix that?

**Comment by sunwrobert** [comment]
Pushed a fix

**Comment by KatFishSnake** [comment]
@sunwrobert sorry should have mentioned that i would take a look at it today, thank you for doing this 🙏
