### ISSUE TITLE
Supports Polygon Network?

### ISSUE THREAD

**Issue by myst4** [ProjectOpenSea/seaport-js#85]
hello there, I want to know if this project is already supporting polygon network? 
Let me explain my situation:
I have a collection of nft on the polygon network and I would like to create a marketplace using the opensea sdk, but I read that opensea-js does not support polygon, I wanted to know if seaport-js supports it, I could not find any information about it

in case that not support polygon, can you recommend me some idea to build my marketnft on my site using opensea below

thanks for advance!

**Comment by sunwrobert** [comment]
It should support polygon yes, just provide it with a provider connected to Polygon
