### ISSUE TITLE
can't install dependencies on macOs

### ISSUE THREAD

**Issue by qweblessed** [ProjectOpenSea/seaport-js#87]
following your guide after git clone && cd seaport-js,I'm not able to install dependencies(npm install)

**Comment by qweblessed** [comment]
facing this:
npm ERR! .git can't be found (see https://git.io/Jc3F9)
npm ERR! npm ERR! code 1

**Comment by sunwrobert** [comment]
Works fine for me on macOS, can you try to repro this with a fresh install of npm/node? Use nvm to help isolate the issue. Closing for now unless there are others that report this.
