### ISSUE TITLE
Troubles with front-end integration

### ISSUE THREAD

**Issue by punpom** [ProjectOpenSea/seaport-js#91]
### Discussed in https://github.com/ProjectOpenSea/seaport-js/discussions/90

<div type='discussions-op-text'>

<sup>Originally posted by **punpom** August 10, 2022</sup>
Hello, I try to use seaportJS with front-end, but my transaction is reverted with this error:  

```
(index.ts:261 Uncaught (in promise) Error: call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="isApprovedForAll(address,address)", data="0x", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.6.4)
    at Logger.makeError (index.ts:261:1)
    at Logger.throwError (index.ts:273:1)
    at Interface.decodeFunctionResult (interface.ts:427:1)
    at Contract.<anonymous> (index.ts:400:1)
    at Generator.next (<anonymous>)
    at fulfilled (index.ts:2:1))
```

I first tried to create a Seaport instance with Metamask and got the above error, and then with a provider and a private key and also got the above error.

I also tried to do an Approveforall from the NFT contract on Etherscan Goerli but nothing works.

I tried a strong approach, approving the NFT contract with the method "isApprovedForAll(address,address)"
and still the same error.

I already made back-end scripts with nodeJS that work perfectly but impossible to allow compatibility between React and SeaportJS.

_I observed that by removing the createOrder function I had no error_

Thank you for reading me</div>

**Comment by bartttiii** [comment]
@punpom Did you manage to fix this?
