### ISSUE TITLE
Can't create sell orders (listings) that reflect on OpenSea

### ISSUE THREAD

**Issue by ajaybha** [ProjectOpenSea/seaport-js#92]
Thanks for this library, it looks very promising (esp. with support of ethers and different networks like Polygon) which are missing in OpenSea.js SDK. 

I am trying to use this to create sellorder/listings in bulk for a ERC721 contract. Though the transaction succeeds, there is no sale listing created for the said item on OpenSea.  

But if I follow the create Order with fullfill orders (as in sample), the sale is reflected in OpenSea and I can see Transfer of the token between offerrer and fulfiller. 

Chain: Polygon Mumbai 
Contract: ERC721 - deployed and items minted already

-------------------------- code snippet for brevity --------------------------
    const { executeAllActions } = await seaport.createOrder(
        {
            offer: [
                {
                    itemType: ItemType.ERC721,
                    token: deployment.address,
                    identifier: "1",
                }
            ],
            consideration: [
                {
                    amount: ethers.utils.parseEther("0.040").toString(),
                    recipient: offerer,
                }
            ],
        }
    );
    const order: OrderWithCounter = await executeAllActions();
    
    // this part also works well, the token sale is reflected on Open Sea
    /*const { executeAllActions: executeFullfillActions} = 
        await seaport.fulfillOrder({
            order,
            accountAddress:fulfiller,
        });
    const txn = await executeFullfillActions();
    console.log(`transaction hash:${txn.hash}`);*/
    
    // this goes through, I can see the transaction on polygonscan, but the sale listing is not created on OpenSea
    const txmethod = await seaport.validate([order]);
    await txmethod.buildTransaction()
    const tx = await txmethod.transact();
    console.log(`Transaction Hash:${tx.hash}`);
    await tx.wait();

**Comment by sunwrobert** [comment]
You need to use `opensea-js` to post orders to OpenSea.

**Comment by ajaybha** [comment]
@sunwrobert Just so I am clear on this....
1. So as of today, if I just want to post order (w/o fulfilling), I have to use opensea.js
2. I was able to post order & fulfill them together through seaport and it reflected on OpenSea as a completed sale transaction

This is a bit confusing to me. Also, given that opensea.js doesn't support Polygon,  folks who want to create bulk sale listings are left high & dry :-(

Is there any thought of making this scenario work with seaport.js such that it reflects on opensea?
Thanks.

**Comment by sunwrobert** [comment]
seaport js isn't related to OpenSea, instead it's a generic helper library to deal with the seaport contract. Opensea js will have polygon support in due time.

**Comment by UmerKhanWazir** [comment]
@sunwrobert To list NFT i'm using opensea "create a list". All the errors from my side are solved and now it gives this error "We encountered an exception while processing your request. Please try again later." with error:500
I am currently sending the request from the opensea documentation section where opensea has this feature of sending request. Need help here.

**Comment by UmerKhanWazir** [comment]
> @sunwrobert To list NFT i'm using opensea "create a list". All the errors from my side are solved and now it gives this error "We encountered an exception while processing your request. Please try again later." with error:500 I am currently sending the request from the opensea documentation section where opensea has this feature of sending request. Need help here.

Solved just had to convert the starttime and endtime in seconds instead of miliseconds/nanoseconds
