### ISSUE TITLE
iOS App Link Constraints

### ISSUE THREAD

**Issue by winchell** [ProjectOpenSea/seaport-js#94]
https://docs.walletconnect.com/mobile-linking#ios-app-link-constraints

Library suffers from this issue by design in that seaport-js can do a lot of nice work after the click and before requesting signatures from the user. This issue more or less completely breaks a dapp on iOS. Once you're bounced into the App Store instead of the crypto wallet, the UX is 💀  and in many cases it's not possible to complete the operation even if you know all about this ~~bug~~ constraint. 

The best immediate solution seems to be to clean bounce users into the built-in MetaMask or Coinbase browsers from the start, where app linking isn't needed.  I'm not sure why OpenSea.io  (and many other sites) aren't doing that.  

It's technically possible to make it work if all the Apple rules are followed. For an example of something that doesn't have this issue, check Uniswap on an iOS browser.

**Comment by sunwrobert** [comment]
We could use `sendUncheckedTransaction`, which should help based on the document?

**Comment by winchell** [comment]
Sure, it would be cool if that's all that's requried. I'd be surprised though. It seems like iOS wants nothing happening between the user interaction and the app switch for it to work properly. Can't say I understand why it goes to the App Store when tripping over this "constraint" but apparently this has been the behavior for years.
